name: Build Plugin

on:
  workflow_dispatch: # 允许手动点击运行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: feat/support-v0.26.1

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
            node-version: "20.x"
            cache: yarn

      - name: Build plugin
        run: |
            git config --global url."https://github.com/".insteadOf ssh://git@github.com/
            yarn install
            yarn run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: obsidian-memos-sync-v0.26.1
          path: |
            main.js
            manifest.json
            styles.css
